apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app                 # Selects Pods with label `app: my-app`
  ports:
    - protocol: TCP
      port: 80                 # Port on the service
      targetPort: 80           # Port on the Pod container
  type: ClusterIP              # Service type: ClusterIP, NodePort, LoadBalancer
